-- FINTECH - Schema (Oracle) | Tabelas: USUARIO, CONTA, DESPESA

-- DROPs seguros (ignoram erro de "table or view does not exist")
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DESPESA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONTA   CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- 1) USUARIO
CREATE TABLE USUARIO (
  ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME           VARCHAR2(100) NOT NULL,
  EMAIL          VARCHAR2(120) NOT NULL,
  SENHA          VARCHAR2(120) NOT NULL,
  DATA_CADASTRO  DATE DEFAULT SYSDATE
);
ALTER TABLE USUARIO ADD CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL);

-- 2) CONTA
CREATE TABLE CONTA (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_USUARIO   NUMBER NOT NULL,
  TIPO         VARCHAR2(30),
  AGENCIA      VARCHAR2(20),
  NUMERO       VARCHAR2(30),
  SALDO        NUMBER(15,2) DEFAULT 0
);
ALTER TABLE CONTA
  ADD CONSTRAINT FK_CONTA_USUARIO
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID);
CREATE INDEX IDX_CONTA_USUARIO ON CONTA(ID_USUARIO);

-- 3) DESPESA
CREATE TABLE DESPESA (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_USUARIO    NUMBER NOT NULL,
  DESCRICAO     VARCHAR2(200),
  VALOR         NUMBER(15,2) NOT NULL,
  DATA_DESPESA  DATE DEFAULT SYSDATE,
  CATEGORIA     VARCHAR2(60)
);
ALTER TABLE DESPESA
  ADD CONSTRAINT FK_DESPESA_USUARIO
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID);
CREATE INDEX IDX_DESPESA_USUARIO ON DESPESA(ID_USUARIO);
